/**
 * @module src/bondService
 * @description
 * This module provides a service layer for interacting with the Daml ledger
 * to query bond portfolio, coupon schedules, and redemption history. It abstracts
 * the ledger interaction logic and transforms the Daml contract data into a
 * format more suitable for the frontend UI.
 */

import { Ledger } from "@c7/ledger";

// --- DAML Codegen Imports ---
// These imports are generated by `dpm codegen-js`. The path depends on the
// package name and version in your `daml.yaml` file.
// We assume the project name is 'canton-bond-issuance' and version is '0.1.0'.
import { BondHolding } from "@daml.js/canton-bond-issuance-0.1.0/lib/Bond";
import { CouponPayment } from "@daml.js/canton-bond-issuance-0.1.0/lib/CouponPayment";
import { RedemptionReceipt } from "@daml.js/canton-bond-issuance-0.1.0/lib/Redemption";
import { Party } from "@daml/types";

// --- Frontend Data-Transfer-Object (DTO) Types ---
// These interfaces define the shape of data used by the UI components.

export interface PortfolioBond {
  contractId: string;
  cusip: string;
  issuer: Party;
  faceValue: number;
  couponRate: number;
  maturityDate: Date;
  // This is an assumption based on a common bond data model.
  paymentFrequency: string;
}

export interface UpcomingCoupon {
  contractId: string;
  cusip: string;
  paymentDate: Date;
  amount: number;
  // If the CouponPayment contract is active, it is by definition unpaid.
  isPaid: false;
}

export interface RedemptionHistoryItem {
    contractId: string;
    cusip: string;
    issuer: Party;
    principalAmount: number;
    redemptionDate: Date;
}

// --- Service Implementation ---

export const bondService = {
  /**
   * Fetches the active bond holdings for the party associated with the ledger's token.
   * @param ledger - An authenticated `@c7/ledger` instance.
   * @returns A promise that resolves to an array of portfolio bonds.
   */
  getBondPortfolio: async (ledger: Ledger): Promise<PortfolioBond[]> => {
    const holdings = await ledger.query<BondHolding>({ templateId: BondHolding.templateId });

    // Map the raw Daml contract data to a cleaner format for the UI.
    // This includes converting Daml's Decimal and Date string formats to JS numbers and Date objects.
    return holdings.map(contract => ({
      contractId: contract.contractId,
      // The payload structure below assumes the BondHolding template has a nested 'bondId' record
      // containing the static details of the bond instrument.
      cusip: contract.payload.bondId.cusip,
      issuer: contract.payload.issuer,
      faceValue: parseFloat(contract.payload.faceValue),
      couponRate: parseFloat(contract.payload.bondId.couponRate),
      maturityDate: new Date(contract.payload.bondId.maturityDate),
      paymentFrequency: contract.payload.bondId.paymentFrequency,
    }));
  },

  /**
   * Fetches upcoming and past-due (but still active) coupon payments.
   * @param ledger - An authenticated `@c7/ledger` instance.
   * @returns A promise that resolves to an array of coupon payments, sorted by payment date.
   */
  getCouponSchedule: async (ledger: Ledger): Promise<UpcomingCoupon[]> => {
    const coupons = await ledger.query<CouponPayment>({ templateId: CouponPayment.templateId });

    const schedule = coupons.map(contract => ({
      contractId: contract.contractId,
      cusip: contract.payload.cusip,
      paymentDate: new Date(contract.payload.paymentDate),
      amount: parseFloat(contract.payload.amount),
      isPaid: false, // An active CouponPayment contract is an obligation to pay.
    }));

    // Sort by payment date, earliest first, for chronological display.
    return schedule.sort((a, b) => a.paymentDate.getTime() - b.paymentDate.getTime());
  },

  /**
   * Fetches the history of redeemed bonds for the party.
   * @param ledger - An authenticated `@c7/ledger` instance.
   * @returns A promise that resolves to an array of redemption history items, sorted by date.
   */
  getRedemptionHistory: async (ledger: Ledger): Promise<RedemptionHistoryItem[]> => {
    const receipts = await ledger.query<RedemptionReceipt>({ templateId: RedemptionReceipt.templateId });

    const history = receipts.map(contract => ({
        contractId: contract.contractId,
        cusip: contract.payload.cusip,
        issuer: contract.payload.issuer,
        principalAmount: parseFloat(contract.payload.principalAmount),
        redemptionDate: new Date(contract.payload.redemptionDate),
    }));

    // Sort by redemption date, most recent first.
    return history.sort((a, b) => b.redemptionDate.getTime() - a.redemptionDate.getTime());
  }
};